project_id = "araojncyittkahvvpdrn"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-topup-checkout]
    verify_jwt = false
  [functions.payments-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.piverify-create-session]
    verify_jwt = false
  [functions.piverify-webhook]
    verify_jwt = false
